### ISSUE TITLE
ImportError: cannot import name 'codecs'

### ISSUE THREAD

**Issue by hsowa** [dbrgn/RPLCD#92]
I think there is the same issue in 1.21 as in #46 

File "/usr/local/lib/python3.5/dist-packages/RPLCD/lcd.py", line 27, in <module>
    from . import codecs
ImportError: cannot import name 'codecs'

**Comment by dbrgn** [comment]
Python packaging sucks so much :roll_eyes: 

Yep, you're right. The `codecs` directory is not included in the package. I'll try to fix it.

**Comment by dbrgn** [comment]
The bug was introduced in 5e19003. Fixed in 0aec598.

I'll release 1.2.2 in a few minutes. Thanks for the report @hsowa!

**Comment by hsowa** [comment]
Many thanks... best wishes to switzerland...
